//// DAN.bs
////   by Tim Müller
////
//// Example workflow that should be allowed by the checker when the `examples/eflint/no-dan.eflint` policy is used.
//// 

import epi;   // local_compute(), aggregate()


// We do a local compute on two domains first
let local_results := parallel [all] [{
    return local_compute(new Data { name := "st_antonius_ect" });
}, {
    return local_compute(new Data { name := "umc_utrecht_ect" });
}];

// Then we aggregate on a third party (not Dan, that's the important bit!)
#[on("surf")]
let central := aggregate(local_results[0], local_results[1]);

// Return it to the user!
return central;
