// Simple file that implements Rosanne's use-case for the EPI project.
//   by Tim Müller

import epi;

// Do local computation on both the St. Antonius and UMC Utrecht
let res_sta := local_compute(new Data{ name := "st_antonius_ect" });
let res_umc := local_compute(new Data{ name := "umc_utrecht_ect" });

// Do the aggregation step
#[on("surf")]
{
    let res := aggregate(res_sta, res_umc);
    return commit_result("surf_res", res);
}
