// Simple file that implements Rosanne's use-case for the EPI project.
//   by Tim Müller

import epi;

// Do local computation on both the St. Antonius and UMC Utrecht
let res := parallel [all] [{
    return local_compute(new Data{ name := "st_antonius_ect" });
}, {
    return local_compute(new Data{ name := "umc_utrecht_ect" });
}];

// Do the aggregation step
#[on("surf")]
{
    let gres := aggregate(res[0], res[1]);
    return commit_result("surf_res", gres);
}
