// Let's nest a lot
let value := 42;
if (value > 0) {
    if (value > 42) {
        if (value > 84) {
            println("Value is more than 84!");
        } else {
            if (value < 84) {
                println("Value is less than 84!");
            } else {
                println("Value is 84!");
            }
        }
    } else {
        if (value < 42) {
            println("Value is less than 42!");
        } else {
            println("Value is 42!");
        }
    }
} else {
    if (value < 0) {
        println("Value is less than 0!");
        if (value > -42) {
            println("Value is more than -42!");
        } else {
            if (value < -42) {
                println("Value is less than -42!");
            } else {
                println("Value is -42!");
            }
        }
    } else {
        println("Value is 0!");
    }
}
