// Note: uncommenting te second works in full-workflow mode, but fails in REPL-mode. :(

{
    func test(text) {
        print("Test123");
        print(text);
    }
}
// {
//     func test(text) {
//         print("Test321");
//         print(text);
//     }
// }

let i := 1;
let j := i;

// This should error when uncommented // let k := k; // And, fun-fact, these three comments should be allowed while at it >:( // Failed at doing that ;(
