import copy_result;     // copy_result()
import data_init;       // zeroes()

// Initialize some thing
let start := zeroes(16, "vector");

// Use it in parallel
let intermediate := parallel [all] [{
    return copy_result(start);
}, {
    return copy_result(start);
}];

// Use the result
let end1 := copy_result(intermediate[0]);
let end2 := copy_result(intermediate[1]);
commit_result("final_result1", end1);
commit_result("final_result2", end2);

