/// WITHOUT TAGS.bs
///   by Tim Müller
/// 
/// Simple policy file that does _not_ use tags to satisfy the `only-synthetic.eflint` policy
/// (and therefore should trigger a 'deny').
/// 
/// Modelled on the EPI ECT use-case.
/// 

import epi;   // local_compute(), aggregate()


// We do a local compute on two domains first
let local_results := parallel [all] [{
    return local_compute(new Data { name := "st_antonius_ect" });
}, {
    return local_compute(new Data { name := "umc_utrecht_ect" });
}];

// Then we aggregate on a third party (our dearest Dan)
#[on("surf")]
let central := aggregate(local_results[0], local_results[1]);

// Return it to the user!
return central;
